import { z } from "zod";
import { validImageSource } from "./image-source";
import { videoSource } from "./video";
const text = z.string().trim().min(1).max(200);
const description = z.string().trim().max(10000).default("");
const id = z.string().min(1).max(150);
const order = z.coerce.number().int().min(1).max(100000);
const status = z.enum(["DRAFT", "PUBLISHED"]);
export const slugify = (value: string) => value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const slug = z.string().trim().max(150).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use a unique lowercase slug with hyphens.");
const image = z.string().trim().max(2000).default("").refine(v => !v || Boolean(validImageSource(v)), "Use a local /images/ path or HTTPS image URL.");
const optionalNumber = z.preprocess(v => v === "" || v == null ? null : v, z.coerce.number().int().min(0).max(1000000).nullable());
export const courseSchema = z.object({ title: text, slug, shortDescription: description, description, thumbnailUrl: image, level: z.enum(["BEGINNER", "INTERMEDIATE", "ADVANCED"]), status, instructorName: text, estimatedDuration: optionalNumber });
export const moduleSchema = z.object({ courseId: id, title: text, description, order });
export const lessonSchema = z.object({ courseId: id, moduleId: id, title: text, slug, description, videoUrl: z.string().max(2000).refine(v => v === "" || Boolean(videoSource(v)), "Use a valid YouTube URL or direct video URL (.mp4/.webm/.ogv)."), thumbnailUrl: image, durationSeconds: z.coerce.number().int().min(0).max(1000000), order, status }).refine(v => v.status !== "PUBLISHED" || Boolean(v.videoUrl), "Published lessons need a video URL.");
export const questionSchema = z.object({ text, explanation: description, options: z.array(z.object({ text, isCorrect: z.boolean() }).strict()).min(2).max(6) }).refine(q => q.options.filter(o => o.isCorrect).length === 1, "Each question must have exactly one correct option.");
export const quizSchema = z.object({ courseId: id, moduleId: z.string().max(150).default(""), title: text, slug, description, passScore: z.coerce.number().int().min(1).max(100), status, questions: z.array(questionSchema).min(1).max(50).optional() });
export const conditions = ["FIRST_SECTION_COMPLETE", "MODULE_COMPLETE", "COURSE_COMPLETE", "QUIZ_COUNT", "STREAK"] as const;
export const badgeSchema = z.object({ name: text, slug, description, icon: z.enum(["play", "star", "flame", "trophy", "crown"]), conditionType: z.enum(conditions), conditionValue: z.coerce.number().int().min(1).max(100000), status: z.enum(["ACTIVE", "INACTIVE"]) });
export const nodeSchema = z.object({ courseId: id, type: z.enum(["LESSON", "QUIZ", "REWARD"]), title: text, targetId: id });
export const commandSchema = z.object({ entity: z.enum(["course", "module", "lesson", "quiz", "badge", "node"]), operation: z.enum(["save", "delete", "up", "down"]), id: id.optional(), data: z.record(z.string(), z.unknown()).default({}) }).strict();
export type AdminCommand = z.infer<typeof commandSchema>;
export type AdminResult = { error?: string; success?: string; id?: string; url?: string };
