import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { beforeEach, expect, it, vi } from "vitest";
const m = vi.hoisted(() => ({ path: "/login", query: new URLSearchParams() }));
vi.mock("next/navigation", () => ({ usePathname: () => m.path, useSearchParams: () => m.query, unstable_rethrow: vi.fn() }));
vi.mock("@/lib/auth-client", () => ({ authClient: { linkSocial: vi.fn(), signIn: { social: vi.fn() } } }));
vi.mock("@/actions/youtube", () => ({ refreshYouTube: vi.fn(), removeYouTube: vi.fn() }));
vi.mock("@/actions/auth", () => ({ authenticate: vi.fn() }));
vi.mock("@/actions/learning", () => ({ saveProfile: vi.fn() }));
vi.mock("@/lib/current-user", () => ({ requireAdmin: async () => ({ name: "Admin", avatarUrl: null }) }));
vi.mock("@/services/admin-queries", () => ({ adminCourses: async () => [] }));
vi.mock("@/lib/prisma", () => ({ getPrisma: () => ({ lesson: { count: async () => 0 }, user: { count: async () => 0 }, quizAttempt: { groupBy: async () => [] }, enrollment: { groupBy: async () => [] } }) }));
import Menu from "../src/components/landing/Menu";
import Footer from "../src/components/layout/Footer";
import AuthForm from "../src/components/auth/AuthForm";
import YouTubeConnection from "../src/components/profile/YouTubeConnection";
import RecentActivity from "../src/components/profile/RecentActivity";
import ProfileHero from "../src/components/profile/ProfileHero";
import LessonHeader from "../src/components/learn/LessonHeader";
import LessonPlayer from "../src/components/learn/LessonPlayer";
import QuizPreview from "../src/components/landing/QuizPreview";
import AdminPage from "../src/app/admin/page";
import type { ProfileView, LessonView } from "../src/types/learning";
import type { ConnectedChannel } from "../src/lib/youtube-channel";
const channel: ConnectedChannel = { channelId: "UC" + "a".repeat(22), channelTitle: "My actual channel", thumbnailUrl: "https://yt3.googleusercontent.com/photo.jpg", customUrl: "@creator", subscriberCount: null, hiddenSubscriberCount: true, videoCount: "12", viewCount: "12345", connectedAt: "2026-10-01T12:00:00Z", lastSyncedAt: "2026-10-01T12:00:00Z" };
beforeEach(() => { m.path = "/login"; m.query = new URLSearchParams(); });
it("keeps real menu destinations and removes unfinished navigation", () => {
  const html = renderToStaticMarkup(createElement(Menu, { user: { name: "Creator", role: "STUDENT", avatarUrl: null }, isSidebarOpen: true, setisSidebarOpen: vi.fn(), onLogout: vi.fn(), logoutPending: false }));
  for (const path of ["dashboard", "courses", "roadmap", "achievements", "bookmarks", "profile"]) expect(html).toContain(`href="/${path}"`);
  expect(html).not.toMatch(/Community|Creator Tools|Notes|Settings|Library|Progress|Coming Soon/);
});
it("footer contains only actual destinations, without fake social/newsletter controls", () => { const html = renderToStaticMarkup(createElement(Footer)); expect(html).toContain('href="/courses"'); expect(html).not.toMatch(/<button|<input|href="#"|Newsletter|Privacy Policy|Pricing/); });
it("Profile activity has no inactive View All action", () => { expect(renderToStaticMarkup(createElement(RecentActivity, { profileActivity: [] }))).not.toContain("<button"); });
it("Profile keeps editing without an inactive Share Profile action", () => {
  const profile: ProfileView = { name: "Creator", email: "creator@example.test", role: "Creator Member", joined: "Oct 1", avatar: "/images/profiles/frc.PNG", bio: "", progress: 0, completed: 0, total: 0, completedUnits: 0, totalUnits: 0, quizAverage: 0, streak: 0, badges: 0, channel: "Not Connected", subscribers: "Unavailable", videos: "Unavailable", views: "Unavailable", connected: false };
  const html = renderToStaticMarkup(createElement(ProfileHero, { profile })); expect(html).toContain("Edit Profile"); expect(html).not.toContain("Share Profile"); expect(html).not.toContain("YouTube Not Connected");
});
it("lessons keep real learning actions without inactive notes or fake player controls", () => {
  const lesson = { title: "First lesson", module: "Basics", number: 1, moduleNumber: 1, duration: "1 min", status: "In Progress", videoUrl: "", thumbnail: "/images/hero.png" } as LessonView;
  const html = renderToStaticMarkup(createElement(LessonHeader, { lessonPreview: lesson } as Parameters<typeof LessonHeader>[0], createElement("button", { type: "submit" }, "Mark as Complete")));
  expect(html).toContain("Mark as Complete"); expect(html).not.toContain("Download Notes");
  const preview = renderToStaticMarkup(createElement(LessonPlayer, { lessonPreview: lesson })); expect(preview).toContain("Video is not available"); expect(preview).not.toContain("<button");
});
it("landing call-to-action leads to real courses without promising an unimplemented community", () => { const html = renderToStaticMarkup(createElement(QuizPreview)); expect(html).toContain('href="/courses"'); expect(html).not.toContain("exclusive content"); expect(html).not.toContain("Community"); });
it("Admin keeps search and CRUD links while hiding inactive Notifications", async () => { const html = renderToStaticMarkup(await AdminPage()); expect(html).toContain('action="/admin/courses"'); expect(html).toContain('href="/admin/courses/new"'); expect(html).not.toMatch(/Notifications|lucide-bell/); });
it.each(["/login", "/register"])("renders working password forms and configured Google login on %s", path => { m.path = path; const html = renderToStaticMarkup(createElement(AuthForm, { googleEnabled: true })); expect(html).toContain("Continue with Google"); expect(html).toContain('name="password"'); expect(html).toContain('name="email"'); expect(html).not.toContain("Forgot password"); });
it("hides Google login without configuration", () => { expect(renderToStaticMarkup(createElement(AuthForm, { googleEnabled: false }))).not.toContain("Continue with Google"); });
it("disconnected Profile shows the actual optional connection control", () => { const html = renderToStaticMarkup(createElement(YouTubeConnection, { channel: null, enabled: true })); expect(html).toContain("Not Connected"); expect(html).toContain("Connect YouTube"); expect(html).not.toContain("Subscribers"); });
it("unconfigured Profile hides unavailable connection controls", () => { expect(renderToStaticMarkup(createElement(YouTubeConnection, { channel: null, enabled: false }))).toBe(""); });
it("real connected Profile displays stored title/photo, hidden counts and active controls", () => { const html = renderToStaticMarkup(createElement(YouTubeConnection, { channel, enabled: true })); expect(html).toContain("My actual channel"); expect(html).toContain("photo.jpg"); expect(html).toContain("Hidden"); expect(html).toContain("Refresh Channel"); expect(html).toContain("Remove Connection"); expect(html).toContain(`href="https://www.youtube.com/channel/${channel.channelId}"`); expect(html).toContain("Last synced"); expect(html).not.toContain("Manage Connection"); });
it("missing subscriber statistics say Unavailable instead of an invented zero", () => { const html = renderToStaticMarkup(createElement(YouTubeConnection, { channel: { ...channel, hiddenSubscriberCount: false }, enabled: true })); expect(html).toContain("Unavailable"); });
